# Generated by Django 3.2.16 on 2023-02-07 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ціна')),
                ('promotion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='Акція в %')),
                ('description', models.CharField(default='', max_length=1000, verbose_name='Опис')),
                ('diameter', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Ширина')),
                ('booster', models.BooleanField(default=False, verbose_name='Бустер')),
                ('draft', models.BooleanField(default=False, verbose_name='Наявність')),
                ('url', models.SlugField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.service')),
            ],
        ),
    ]
